name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🎉 Release'
    labels:
      - 'release'
      - 'major'
      - 'minor'
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'refactor'
      - 'chore'
      - 'dependencies'
      - 'renovate'
      - 'document'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: patch
autolabeler:
  - label: release
    branch:
      - '/^release[/-].+/'
  - label: feature
    branch:
      - '/^feat(ure)?[/-].+/'
  - label: bug
    branch:
      - '/^fix[/-].+/'
  - label: chore
    branch:
      - '/^chore[/-].+/'
  - label: refactor
    branch:
      - '/(refactor|refactoring)[/-].+/'
  - label: documentation
    branch:
      - '/doc(umentation)[/-].+/'
    files:
      - '*.md'
header: $HEADER
template: |
  ## Changes

  $CHANGES
