name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🎉 Release'
    labels:
      - 'release'
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: patch
template: |
  ## 🧰 Maintenance

  $CHANGES

  **すべての変更点**: $REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
