name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🎉 Release'
    labels:
      - 'release'
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'refactor'
      - 'chore'
      - 'dependencies'
      - 'document'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: patch
autolabeler:
  - label: feature
    branch:
      - '/^feat(ure)?[/-].+/'
      - '/^topic[/-].+/'
  - label: bug
    branch:
      - '/^fix[/-].+/'
  - label: chore
    branch:
      - '/^chore[/-].+/'
  - label: refactor
    branch:
      - '/(refactor|refactoring)[/-].+/'
  - label: documentation
    branch:
      - '/doc(umentation)[/-].+/'
    files:
      - '*.md'
  - label: docker:build
    files:
      - 'infra/docker/*'
  - label: npm:install
    files:
      - 'src/package.json'
      - 'src/package-lock.json'
  - label: composer:install
    files:
      - 'src/composer.json'
      - 'src/composer.lock'
  - label: artisan:migrate
    files:
      - 'src/database/migrations/*'
template: |
  # Changes

  $CHANGES
