name: バグレポート
description: バグレポート用のテンプレート
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        1つのバグに付き、1Issueで報告してください。
        タイトルは簡潔で問題がわかる要約として記述してください。
  - type: textarea
    id: description
    attributes:
      label: 現象
      description: どのようなバグが発生したのか、できるだけ詳細に記述してください。
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順と再現性
      description: |
        そのバグを再現するための手順をできるだけ詳しく記述してください。
        また、再現性がどのくらいあるか記述してください。
      value: |
        1.
        2.
        3.
  - type: textarea
    id: expected
    attributes:
      label: 期待される事象
      description: 本来どのような結果を期待しているのかを記述してください
  - type: textarea
    id: screenshot
    attributes:
      label: スクリーンショット
      description: 問題を示すスクリーンショットがあれば、ここに追加してください。
  - type: checkboxes
    attributes:
      label: どの環境で発生しましたか？
      description: 問題が発生した環境を選択してください。
      options:
        - label: ローカル環境
        - label: 検証環境
        - label: 本番環境
  - type: textarea
    id: logs
    attributes:
      label: ログ
      description: エラー発生時のログがあれば記載して下さい。
      render: shell
  - type: textarea
    id: others
    attributes:
      label: その他
      description: その他、問題に関する情報があればここに追加してください。
