name: AI Code Review
on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]
jobs:
  pr-agent:
    if: ${{ ! contains(github.event.*.labels.*.name, 'ignore-for-ai-code-review') && github.event.sender.type != 'Bot' }}
    permissions:
      issues: write
      pull-requests: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      REVIEW_INSTRUCTIONS: >-
        日本語を使用してください。
        以下に記載した観点からレビューを行ってください。
        ただし、改善点がなければ回答は不要です。
        クエリやEloquentが利用されている場合、以下2つの観点から改善提案してください。
        - クエリそのもののパフォーマンス改善
        - 検索対象テーブルにインデックスを追加すべきカラムがあるか
        その他ファイル対して、以下の観点でレビューしてください。
        - 命名は分かりやすく実態を表しているか
        - typo
        - 可読性
        - セキュリティ上の脆弱性がないか
        - トランザクションの貼り方が適切か
        - 理解しにくい、または実装と命名が乖離している箇所があるか
        - クラス名、関数名、変数名により適切なものがあるか
        - 関数名だけで実装が理解しにくい場合、分かりやすい日本語でコメントされているか
        - クリーンアーキテクチャやドメイン駆動設計の観点から指摘はあるか
        - 冗長なコードがないか
        - ネストが深い（3以上）条件文などがないか
        - コーディング規約を守れているか
        - ファイル末尾に改行が入れられているか
    steps:
      - uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          litellm.drop_params: 'true'
          # レビューの労力見積もりを必須としない
          pr_reviewer.require_estimate_effort_to_review: 'false'
          # ファイル要約をインライン表示する設定が有効になっています
          pr_description.inline_file_summary: 'false'
          # 説明マーカーの使用を無効化しています
          pr_description.use_description_markers: 'false'
          # 「Generated by」ヘッダーの追加を無効化しています
          pr_description.include_generated_by_header: 'false'
          # 最終更新メッセージの表示を無効化しています
          pr_description.final_update_message: 'false'
          # ヘルプテキストの表示を無効化しています
          pr_description.enable_help_text: 'false'
          # 自動レビュー機能を有効化しています
          github_action_config.auto_review: 'true'
          # 自動説明生成機能を有効化しています
          github_action_config.auto_describe: 'false'
          # 自動改善機能を有効化しています
          github_action_config.auto_improve: 'true'
          # レビュワーには回答を日本語で行うよう指示しています
          pr_reviewer.extra_instructions: ${{ env.REVIEW_INSTRUCTIONS }}
          # コード提案のは回答を日本語で行うよう指示しています
          pr_code_suggestions.extra_instructions: ${{ env.REVIEW_INSTRUCTIONS }}
          # 自動で生成されるラベルを無効化
          pr_description.publish_labels: 'false'
          pr_reviewer.enable_review_labels_security: 'false'
          pr_reviewer.enable_review_labels_effort: 'false'
