name: Assign author to Pull Request
on:
  pull_request:
    types: [opened]
jobs:
  assign-author:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
