name: Assign author to Issue
on:
  issues:
    types: [opened]
jobs:
  assign-author:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
