name: Code Review
on:
  pull_request:
    types: [opened] # PR作成の初回のみレビューする。
jobs:
  code-review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Japanese
          MODEL: gpt-4-0125-preview # https://platform.openai.com/docs/models/overview
