name: Integration Pull Request
on:
  pull_request:
    types: [synchronize, opened, reopened]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: exit 0
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: github.event.pull_request.base.sha
        run: echo ${{ github.event.pull_request.base.sha }}
      - name: github.event.pull_request.base.sha
        run: echo ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
      - name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
