name: Update Labels

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  label:
    permissions:
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: yarn add -D @azu/github-label-setup

    - name: Update Labels
      run: yarn github-label-setup --token ${{ secrets.GITHUB_TOKEN }} --labels .github/labels.json
